oath_proxy:
  build: .
  ports:
   - "5000:5000"
  volumes:
   - .:/code
  environment:
    - OAUTH_PROXY_BASE_URL=https://api.github.com/
    - OAUTH_PROXY_CONSUMER_KEY=
    - OAUTH_PROXY_CONSUMER_SECRET=
    - OAUTH_PROXY_TOKEN=
    - OAUTH_PROXY_TOKEN_SECRET=
